### ISSUE TITLE
Add argument for align_taxa() function to specify output location

### ISSUE THREAD

**Issue by rubysaltbush** [traitecoevo/apcnames#6]
The update_taxonomy() function takes an argument output = x to specify the location and name of the .csv file written by that function, so that the csv file is not just written to the working directory.

Is it possible to add a similar output = x argument to the align_taxa() function, which currently automatically writes "taxonomic_updates.csv" to the working directory?

**Comment by dfalster** [comment]
Done. Check changes in commit above. Note also, saving to file is now an optional extra, so you need to specify filenames for both functions: `align_taxa` & `update_taxonomy`

**Comment by rubysaltbush** [comment]
Awesome thanks Daniel!
