### ISSUE TITLE
`update_taxonomy` returns some duplicate rows

### ISSUE THREAD

**Issue by rubysaltbush** [traitecoevo/apcnames#8]
The `update_taxonomy` function returned duplicate rows for two species in my data set - both orchids matched via APNI (Caladenia tentaculata and Pterostylis aff. nana). I suspect this is because of problematic taxonomy for these taxa leading to duplicated records in APNI. The duplicate rows are identical in each column so I have removed them by calling `dplyr::distinct` on the output from `update_taxonomy`, not sure if this could/should be worked into the function or not.

**Comment by dfalster** [comment]
Great idea Ruby. Next GitHub challenge for you - want to fork the repro, make the change and send a pull request?

**Comment by rubysaltbush** [comment]
Done thanks Daniel!

**Comment by dfalster** [comment]
Awesome Ruby! 

One very minor suggestion is add the issue number in your commit message, as automatically cross links to the issue.
